baseURL = "https://madai.es"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
buildFuture = true

[languages]
    [languages.es]
      disabled = false
      languageCode = 'es'
      languageName = 'ES'
      weight = 1
    [languages.en]
      disabled = false
      languageCode = 'en'
      languageName = 'EN'
      weight = 2
[markup]
    defaultMarkdownHandler = 'goldmark'

[outputs]
    home = ['html', 'llms']

[outputFormats.llms]
    mediaType = 'text/plain'
    baseName = 'llms'
    isPlainText = true
    notAlternative = true
